networks:
  toubilib.net:
    driver: bridge

services:
  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubilib:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprat.db
      - toubiauth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"

    # service toubiprat.db : base de données postgresql pour les praticiens

  toubiprat.db:
    image: 'postgres:latest'
    env_file: ./env/toubipratdb.env
    ports:
      - '5432:5432'
    networks:
      - toubilib.net
    volumes:
      # - ./sql:/var/sql
      - ./sql/prati:/docker-entrypoint-initdb.d/

  toubiauth.db:
    image: 'postgres:latest'
    env_file: ./env/toubiauthdb.env
    ports:
      - '5436:5432'
    networks:
      - toubilib.net
    volumes:
     # - ./sql:/var/sql
      - ./sql/auth:/docker-entrypoint-initdb.d/


  toubirdv.db:
    image: 'postgres:latest'
    env_file: ./env/toubirdvdb.env
    ports:
       - '5434:5432' 
    networks: 
       - toubilib.net
    volumes:
      # - ./sql:/var/sql
       - ./sql/rdv:/docker-entrypoint-initdb.d/

  toubipat.db: 
    image: 'postgres:latest'
    env_file: ./env/toubipatdb.env
    ports:
      - '5438:5432'
    networks:
      - toubilib.net
    volumes:
      # - ./sql:/var/sql
      - ./sql/pat:/docker-entrypoint-initdb.d/

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubilib.net

